all:
	#g++ -std=c++20 -Ofast -flto bits.cpp board.cpp evaluation.cpp hashKey.cpp main.cpp moveGenerator.cpp perft.cpp search.cpp state.cpp staticExchangeEvaluation.cpp table.cpp updateState.cpp -o ChandraChess -Bstatic
	x86_64-w64-mingw32-g++ -std=c++20 -Ofast -flto bits.cpp board.cpp evaluation.cpp hashKey.cpp main.cpp moveGenerator.cpp perft.cpp search.cpp state.cpp staticExchangeEvaluation.cpp table.cpp updateState.cpp -o ChandraChess.exe -Bstatic
	#g++ -std=c++20 -Ofast -flto shuffle.cpp -o a -Bstatic
	#g++ -std=c++20 -Ofast -flto train.cpp -o a -Bstatic
	#g++ -std=c++20 -Ofast -flto bits.cpp board.cpp evaluation.cpp hashKey.cpp moveGenerator.cpp perft.cpp pgnExtract.cpp state.cpp staticExchangeEvaluation.cpp table.cpp updateState.cpp -o a -Bstatic
	./ChandraChess
	#./a